language: node_js
branches:
  only:
  - master
services:
- mongodb
before_script:
- npm i -g lerna
- npm i -g node-sass
script:
- yarn run bootstrap
- yarn run build
- yarn run css
- yarn run ci
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    rooms:
    - engagelab:s6lOlE0DN0Drfzyo2fBtPuch#code
    - engagelab:s6lOlE0DN0Drfzyo2fBtPuch#el-api-dev
env:
  global:
  - secure: sWTKSo9up6/s+a7sYJQqitQmiplYj4BvbyGvj8tOM/auDeUMgerjI9Veq/WaK9hzKAm+IDuPLrzRYhXBuxSLIprkcphJksACATt10CvSkf38lQbzxhYJh7gRhi9QC3L3g/1BFUFcW8HfYqQy78Mw2+XfwPBk1BskI1wKdKEOYWkAklcCtGjmhWsJfagq9axMoa+23NN9ZD5snFwBspmMYhJPlgq83xKWiBWWY2nvUv1W2DuZ7d8Pcojbd10b48alJu9FItr3jtqCXojvQRSg3Ttaz9GO2xOxrOGcEXFvrIGBhK8yR07/vut9GMyHYjlXdg8TfeSHVWWjDjygce7c/vglqUl6wpM6AYMA/8Yb0xdVzYb76tIECAZTvT02DTp7BvptQ8RA+yf+wKV+QTzl3ug5j87ydNaFE8NzNMVKUlvHNwoSx4OSvWExg8VaXZdSdlHw3zGnB4/T4BQ/oG0er0KnXdGT9ByQ2y0NRNcPjPnrCjbTJ/9in4viWB3htXLRUPpW9Z+jQ7S4LXy3/AcT3WCAHjR+djWzyOmuFAja2FD9f07mpDc6ZCXxN+Iic50s07JLvS2b687mFEqnmGp2PMtT/ImHQZUiULo0F9M4ut/pQt0x8yGlH0GdQzr+2uXhIFYO4xsZGsx2fZtnUh606Miawa1a4Wd+DbhexfPIDu4=
  - secure: G26nDS1JxQRimfsAkiF1VKgyKrNaPqEwRI4psujIdU+zjOOUaBd2bje4bNWMiXMfpHw9FoYqRe62GsDcnxUTT8mIoOKyYgg5WQgBs+IeXiZSx4oPfYwMeFMyJPzlEM9s0/UW5ndQzV80mTQUjMugRT3S/aelW24r+xXtaQaAqdKNQfw5fOwbmqGc1mtJR8bZaeg9FO6ySO5AUA5Bn2agCel935ZLV9dz4QukBTkOFIwE2UU2gGFztCOg59ntfx1gokrDypYVk77auma3Sw1egL5M/WCkr6kuc8w4cJbTL2aAQWyjtrC1UEF2W/Mzit/VrGrkeU49lqzoCMqvahpI2BQAH7ocqX3RLL4ouMK3kyD7CKJyNAOrg+PuZIWKgTXNpK86LQmBx8bvjrOBAO+iChRQ2ZvqkdVtmbnFuM7NBXUVE0ozFO+/M9c41XzMdCK4Y42k/6Ntm6ICJ9u7eSVdfdymS3S/JjMe7iVVTweHpJq1qXnDOP10bD5kpWRY/v2qWxpJVq9a35hWe5K6uSv61TuPPiKbfF9HdtmL4lMiUFm9JCJzpemZOealyfZ9GpolbWSk+uA7ehf1Z2pJ/72/czHwA33E92ibKDW5LFecsIiy9jERRpowyymGuyAC0dccueGJZyw3IKy/GZf0YpQDS015H04CMVjMIe3K8woqjTo=
  - secure: nvuKWrIOrMiCnPcrwVC5T17GVLppVa6S3sAErCBTN3clF4yGs1EunOA1ZhEKoXBNLxBAjY2K+8hdkAG1VOv7oNtfnOBjJ9U4MCLZI2vRHZ7QAd7dmowYWIPjECCkw2lTvsk8ghI1M+J8mkaWlQ3ATMvq6hzxRHM4ijFDWU4evtknIfmNcNGUCGe1AYw703MUapQYO/SAqbGEw8MSzhYRcbLnJyT+ZPWguse9szmZ+r4P7fvVY+0H5D5vlYKGZvwTjQqCOWHYoHbp0Psydjd5cNXzIEzubNv7Fv9kX/jGFqjn3uB7vOi8S9aF8YHonjJE52BDmgqvkwUHLZJdrdUKzgyVgBxIIgOfMyBXT21drZCqP1KxqO1A25Zq5CFobgYH6tiWa5Inww8+igXl6k3zIdMX1FcTY1P3FuKtjJXPOmhlPYHplX+8zpTtMfO8dDPRFLY0KyYeLbCyu84Vqd9QSWkAoZMRV7bjxDEXUlIu4PhiphngFeXiL9spC/yfgA1pAGOwUTO8teWAN/7Y+FYKb87IIoliW87YSsse0eo+3upZycHpEVHcqXNzhfAcZbx6nXG25/zXazJvhz2xdvLMCMyRIdRf1GC099gtUG/MnGUiFhaNLkL+6DxEOg/sjv/ckafJOS5Y8jLo3dbyegZoPv8frgWr9g3johgyJFav798=
