language: node_js

branches:
  only:
    - master

before_script:
  - npm i -g lerna

script:
  - yarn run bootstrap
  - yarn run ci
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      - engagelab:s6lOlE0DN0Drfzyo2fBtPuch#code
      - engagelab:s6lOlE0DN0Drfzyo2fBtPuch#el-api-dev
